export const ROADMAPS = [
    {
      id: "python-ds",
      iconName: "python",
      iconBg: "#EEF2FF",
      accentColor: "#7AE84A",
      title: "Python for Data Science",
      subtitle: "Master core libraries and analytical workflows for modern data science.",
      status: "in-progress",
      progress: 64,
      modules: [
        {
          id: "m1",
          title: "Module 1: Python Basics",
          subtitle: "Syntax, variables, and primitive data types.",
          xp: 150,
          time: "2h 30m",
          status: "completed",
          lessons: [
            { id: "l1", title: "Variables & Data Types", status: "completed" },
            { id: "l2", title: "Control Flow & Loops",  status: "completed" },
            { id: "l3", title: "Functions Intro",        status: "completed" },
          ],
        },
        {
          id: "m2",
          title: "Module 2: Functions & Modules",
          subtitle: "Building reusable logic and managing project structure.",
          xp: 250,
          time: "4h 15m",
          status: "in-progress",
          lessons: [
            { id: "l4", title: "Defining Custom Functions",  status: "in-progress", resumeLabel: "Resume" },
            { id: "l5", title: "Arguments & Return Values",  status: "locked" },
            { id: "l6", title: "Importing Standard Modules", status: "locked" },
          ],
          nextConcept: {
            title: "Scope and Lambda Expressions",
            desc: "Understand global vs local namespace and how to write concise anonymous functions.",
          },
        },
        {
          id: "m3",
          title: "Module 3: NumPy & Data Arrays",
          subtitle: "Foundations of numerical computing in Python.",
          xp: 400,
          time: "5h 45m",
          status: "locked",
          lessons: [],
        },
        {
          id: "m4",
          title: "Module 4: Pandas for Data Wrangling",
          subtitle: "DataFrames, Series, and complex data manipulation.",
          xp: 500,
          time: "8h 20m",
          status: "locked",
          lessons: [],
        },
        {
          id: "m5",
          title: "Module 5: Data Visualisation",
          subtitle: "Matplotlib, Seaborn, and storytelling with charts.",
          xp: 350,
          time: "4h 00m",
          status: "locked",
          lessons: [],
        },
      ],
    },
    {
      id: "ux-figma",
      iconName: "design",
      iconBg: "#FDF4FF",
      accentColor: "#a78bfa",
      title: "UI/UX Design with Figma",
      subtitle: "Go from wireframes to polished prototypes with modern design thinking.",
      status: "in-progress",
      progress: 35,
      modules: [
        {
          id: "u1",
          title: "Module 1: Design Fundamentals",
          subtitle: "Colour theory, typography, and layout principles.",
          xp: 120,
          time: "2h 00m",
          status: "completed",
          lessons: [
            { id: "ul1", title: "Colour & Contrast",  status: "completed" },
            { id: "ul2", title: "Typography Basics",  status: "completed" },
            { id: "ul3", title: "Grid & Spacing",     status: "completed" },
          ],
        },
        {
          id: "u2",
          title: "Module 2: Figma Essentials",
          subtitle: "Frames, components, auto-layout, and variants.",
          xp: 200,
          time: "3h 30m",
          status: "in-progress",
          lessons: [
            { id: "ul4", title: "Frames & Groups",       status: "in-progress", resumeLabel: "Resume" },
            { id: "ul5", title: "Components & Variants", status: "locked" },
            { id: "ul6", title: "Auto-layout Deep Dive", status: "locked" },
          ],
          nextConcept: {
            title: "Components & Variants",
            desc: "Build a scalable design system using reusable components and variant states.",
          },
        },
        {
          id: "u3",
          title: "Module 3: Prototyping & Interactions",
          subtitle: "Clickable prototypes and micro-interaction design.",
          xp: 280,
          time: "4h 00m",
          status: "locked",
          lessons: [],
        },
        {
          id: "u4",
          title: "Module 4: User Research",
          subtitle: "Interviews, usability testing, and synthesis.",
          xp: 200,
          time: "3h 00m",
          status: "locked",
          lessons: [],
        },
      ],
    },
    {
      id: "data-viz",
      iconName: "dataViz",
      iconBg: "#ECFDF5",
      accentColor: "#10b981",
      title: "Data Visualisation Basics",
      subtitle: "Turn raw numbers into compelling visual stories.",
      status: "completed",
      progress: 100,
      modules: [
        {
          id: "d1", title: "Module 1: Chart Fundamentals", subtitle: "Bar, line, scatter, and pie charts.",
          xp: 100, time: "1h 30m", status: "completed",
          lessons: [
            { id: "dl1", title: "Choosing the Right Chart", status: "completed" },
            { id: "dl2", title: "Axes & Labels",            status: "completed" },
          ],
        },
        {
          id: "d2", title: "Module 2: Matplotlib", subtitle: "Python's foundational plotting library.",
          xp: 150, time: "2h 00m", status: "completed",
          lessons: [
            { id: "dl3", title: "Pyplot Basics",      status: "completed" },
            { id: "dl4", title: "Subplots & Figures", status: "completed" },
          ],
        },
        {
          id: "d3", title: "Module 3: Seaborn", subtitle: "Statistical visualisation made elegant.",
          xp: 180, time: "2h 30m", status: "completed",
          lessons: [
            { id: "dl5", title: "Distribution Plots", status: "completed" },
            { id: "dl6", title: "Heatmaps",           status: "completed" },
          ],
        },
        {
          id: "d4", title: "Module 4: Final Project", subtitle: "End-to-end data story with a real dataset.",
          xp: 300, time: "4h 00m", status: "completed",
          lessons: [{ id: "dl7", title: "Project Submission", status: "completed" }],
        },
      ],
    },
    {
      id: "ml-basics",
      iconName: "ml",
      iconBg: "#F0F9FF",
      accentColor: "#0ea5e9",
      title: "Machine Learning Fundamentals",
      subtitle: "Understand the algorithms powering modern AI applications.",
      status: "saved",
      progress: 0,
      modules: [
        { id: "ml1", title: "Module 1: Math Refresher",        subtitle: "Linear algebra and statistics for ML.", xp: 150, time: "3h 00m", status: "locked", lessons: [] },
        { id: "ml2", title: "Module 2: Supervised Learning",   subtitle: "Regression, classification, and evaluation.", xp: 300, time: "6h 00m", status: "locked", lessons: [] },
        { id: "ml3", title: "Module 3: Unsupervised Learning", subtitle: "Clustering, dimensionality reduction.", xp: 280, time: "5h 00m", status: "locked", lessons: [] },
        { id: "ml4", title: "Module 4: Neural Networks",       subtitle: "Perceptrons, backpropagation, and deep learning intro.", xp: 400, time: "7h 00m", status: "locked", lessons: [] },
        { id: "ml5", title: "Module 5: ML Project",            subtitle: "Build and deploy a real ML model.", xp: 500, time: "8h 00m", status: "locked", lessons: [] },
      ],
    },
  ];